### PR TITLE
Using single session for connections

### PR DESCRIPTION
**Pull request by KarthikMasi**
In logs, a new https connection was started for every request. Tried re-using a session instead and the connections were faster.

### CODE REVIEW

**Comment by sburns** [comment]
Interesting, but based on CI it seems like the response headers have been lost or moved somewhere else where we're not expecting them.

**Comment by sburns** [comment]
In general, are you trying to import/export stuff in a tight loop or within a web request? Just curious about your use case that you went about hunting for this slowness.

**Comment by KarthikMasi** [comment]
> In general, are you trying to import/export stuff in a tight loop or within a web request? Just curious about your use case that you went about hunting for this slowness.

It was not that the connections were slow before. I just saw that there were new connections started for every request and thought that re-using the sessions might be a slight improvement. Also, in our use case, we have one export per code run-time. We had multiple cronjobs making requests to the REDCap database simultaneously and we needed to bring down the number of overall new connections submitted from the user. 

As for the response headers, I committed an unsaved file. Sorry about that. I shall update it.

**Comment by pwildenhain** [comment]
This looks good to me, though there seem to be changes in here related to deleting a record? Are there changes in here from #77? I would feel good about merging if those changes weren't in here

**Comment by pwildenhain** [comment]
@KarthikMasi Thanks again for submitting these changes! I opened up a PR to get this updated from the current master branch -- would you be able to merge? KarthikMasi#1

**Comment by pwildenhain** [comment]
This was resolved in #120

**Pull request closed without merging**
