### PR TITLE
Adding in new delete functionality

### PR DESCRIPTION
**Pull request by damonms**
Hi Scott,

Here's my stab at adding in the new functionality to delete a record. I haven't updated the docs (just the readme currently). Let me know what you think / want fixed. Happy to review.

Cheers,
Steve

### CODE REVIEW

**Comment by bobromeo** [comment]
I am a noob on GitHub, but is this PR hanging on update of the update of the README.rst ?!?

**Comment by pwildenhain** [comment]
📝 For what it's worth -- this PR could easily be updated to allow for the deletion of multiple records.

Changing the body of the POST request from `records[0]` to `records[]` allows an array of records to be passed, rather than just one record at a time ✨

**Comment by damonms** [comment]
I no longer have a valid REDCap API token to test against, but this seems reasonable if someone else can validate / wants to take over this PR and branch

**Comment by sburns** [comment]
> I am a noob on GitHub, but is this PR hanging on update of the update of the README.rst ?!?

this PR is hanging out because I've moved on in my career and don't use pycap for my day job anymore :)

**Comment by pwildenhain** [comment]
> this PR is hanging out because I've moved on in my career and don't use pycap for my day job anymore :)

My colleague @gammaflauge and I are currently _heavy_ users of this package. Would you be open to us collaborating on this package?

**Comment by sburns** [comment]
Absolutely! I think this PR needs back-merged with master. IIRC we don't actually hit any particular endpoint across the internet during tests.

**Comment by pwildenhain** [comment]
@damonms I opened up a PR to get this updated from the current `master` branch -- would you be able to merge? https://github.com/VUIIS/PyCap/pull/1

**Comment by pwildenhain** [comment]
Thanks for updating 🙇‍♂️ This is good to go :shipit:

**Pull request merged**
