### PR TITLE
Add `repeat_instance` parameter to `imp_file` request

### PR DESCRIPTION
**Pull request by martinburchell**

### CODE REVIEW

**Comment by sburns** [comment]
Hey Martin thanks for the PR? Can you briefly talk about what this does? I'm not using REDCap in my day to day work anymore and there doesn't appear to be public API docs anywhere.

**Comment by martinburchell** [comment]
@sburns I've added the `repeat_instance` parameter which allows you to upload files to instruments that are set up to be repeating. It is an integer that starts at 1. Unfortunately REDCap won't create these automatically as it does with record IDs.

This allows the same record to be updated multiple times. I suppose a use case might be uploading a photo or a scan of a survey on each visit to a patient.

The same exists for `import_records` but the instance id goes into the blob of data, so nothing for PyCap to do there.

Here's a screen grab of the API documentation for our REDCap instance

Screenshot_2019-12-03 REDCap API Documentation

**Comment by sburns** [comment]
So it's on the client to determine what `repeat_instance` should be? I worry people will easily overwrite data but this is more an issue with the API design and not anything PyCap can solve.

**Comment by martinburchell** [comment]
@sburns yes, I've raised this in the (closed) forum https://community.projectredcap.org/questions/74561/unexpected-behaviour-with-import-records-repeat-in.html

**Comment by martinburchell** [comment]
@sburns thanks for taking the time to look at this and merging my other PRs.

I'm keen to get this one through. What needs to happen next?

My request for auto-generated `repeat_instance` has been noted by the REDCap developers and I don't expect anything to happen any time soon. So in the meantime we have to export the records to get the next repeat instance ID and hope no-one else has updated the database in the milliseconds between requests. See https://github.com/RudolfCardinal/camcops/blob/redcap-export/server/camcops_server/cc_modules/cc_redcap.py#L282

**Pull request merged**
