### PR TITLE
Fixes breakage in configure() due to API change

### PR DESCRIPTION
**Pull request by fonnesbeck**
The current Vanderbilt REDCap breaks PyCap master by returning tuples where dicts are expected. This fixes this issue. Also removed mixture of tabs and spaces in `project.py` (spaces only here).

Passes all tests under legacy Python (2.7); still work to be done for Python 3 compatibility.

### CODE REVIEW

**Comment by sburns** [comment]
Thanks @fonnesbeck!

> Also removed mixture of tabs and spaces in project.py (spaces only here).

:frowning: that tabs got there in the first place. Do you want to introduce py3 compatibility in this branch or another PR?

Can some other sites check this out for compatibility? This might be the first time use the site version to our advantage. @pbchase @aaron0browne @dckc

**Comment by fonnesbeck** [comment]
I will get around to Py3 compatibility in another PR. Best to get this working first.

**Comment by sburns** [comment]
@fonnesbeck are you using this branch reliably at Vandy? Also can you back-merge master (@nicholsn provided a PR along the lines of your 4d245b2 change)?

**Comment by fonnesbeck** [comment]
Yes, its working fine. Haven't gone in and done all the Py3 updates that I'd intended, but at least it runs on 2.7.

I will rebase; that should do it, right?

**Comment by fonnesbeck** [comment]
Any chance of getting this merged, or is there more that needs to be done?

**Comment by sburns** [comment]
thanks for the PR @fonnesbeck!

**Comment by dgutman** [comment]
Has anyone been able to connect to 6.5.0 using the pycap API?  I am having
some connection issues, although I can still connect to one of my older
redcap systems, and I also tried to connect via the Chrome ADVANCED REST
Client and it seems like my token works...

**Comment by pbchase** [comment]
PyCap definitely worked on 6.5.x for us.  I don't recall which 6.5.x, but
we ran 6.5 for a while with no PyCap problems.

Philip

On Mon, Jan 11, 2016 at 2:27 PM dgutman <notifications@github.com> wrote:

> Has anyone been able to connect to 6.5.0 using the pycap API? I am having
> some connection issues, although I can still connect to one of my older
> redcap systems, and I also tried to connect via the Chrome ADVANCED REST
> Client and it seems like my token works...
>
>
>
> On Mon, Oct 5, 2015 at 9:09 PM Chris Fonnesbeck <notifications@github.com>
> wrote:
>
> > The current Vanderbilt REDCap breaks PyCap master by returning tuples
> > where dicts are expected. This fixes this issue. Also removed mixture of
> > tabs and spaces in project.py (spaces only here).
> >
> > Passes all tests under legacy Python (2.7); still work to be done for
> > Python 3 compatibility.
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/sburns/PyCap/pull/59
> > Commit Summary
> >
> > - Fixes breakage in configure() due to API change; progress towards
> > Py3 compatibility
> >
> > File Changes
> >
> > - *M* redcap/project.py
> > <https://github.com/sburns/PyCap/pull/59/files#diff-0> (79)
> >
> > Patch Links:
> >
> > - https://github.com/sburns/PyCap/pull/59.patch
> > - https://github.com/sburns/PyCap/pull/59.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sburns/PyCap/pull/59>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redcap-tools/PyCap/pull/59#issuecomment-170662353>.
>
-- 
Philip Chase * 352-575-0705 * Gainesville, FL

**Pull request merged**
