### PR TITLE
Added REDCap API Changelog and linked in README

### PR DESCRIPTION
**Pull request by SlightlyUnorthodox**
REDCap API Changelog covers all changes made from REDCap 6.0.0 to 6.12.1 (excluding bug fixes, for now) that have any effect on PyCap's use of the REDCap API. Added link in README.

### CODE REVIEW

**Comment by sburns** [comment]
Holy cow this is phenomenal!

**Comment by SlightlyUnorthodox** [comment]
Hope this is at least somewhat helpful, though I realized I probably should have placed it in the docs folder, my bad.

**Comment by sburns** [comment]
Yeah would you mind moving it `/docs` and linking it in `index.rst`. Also, would you add a a small bit at the top saying these are new methods in 6.X.X that we hope to support in the future?

**Comment by SlightlyUnorthodox** [comment]
I went ahead and made the adjustments, I'll go ahead and close this pull request before making a clean, more detailed one.

**Pull request closed without merging**
