### PR TITLE
Add Arm and Event API

### LINKED ISSUE #276: Add Arm API
* Export
* Import
* Delete

### PR DESCRIPTION
**Pull request by patking02**
Fixes #276 and #277 

Adds Arm and Event API methods, tests, and documentation.

I initially was going to separate these two out (one PR for Arm, one for Event), but while writing the tests for Arm, I realized I needed to attach an Event to the Arm in order for the Arm Export to return the newly added arm. If need be, I can do one at a time (I guess Event then Arm), but if it is OK to submit/review both at the same time, then here they are.

I tested the Unit tests, but I did not have access to run the Integration Tests, FYI.

### CODE REVIEW

**Comment by pwildenhain** [comment]
Amazing thank you! I'll take a look at some point this weekend or early next week

**Review by pwildenhain — COMMENTED** [review]
This is truly incredible. Without a doubt, the cleanest PR I've ever received, and especially impressive for a first time contributor. Not only do the code changes mesh _perfectly_ with the rest of the codebase but you also updated **docs** (and **doctests**), **unit tests**, and **integration tests** which are each a world of their own.

I'm super impressed 🤩 If you're ever looking for a job, let me know, you seem like a grade-A coder.

I've made a few updates to the integration/doctests (which was to be expected since you don't have permissions run them) that you can review here: https://github.com/patking02/PyCap/pull/1

Once these are merged, I'll merge this PR and cut a new release pronto ⚡

**Comment by patking02** [comment]
Thanks for the kind words; the PyCap library is well maintained and has a lot of good checks and standards in place that made my job easy.

Happy to help contribute and give back to the community. Thank you for reviewing the PR.

**Review by pwildenhain — APPROVED** [review]
💯 👏🏻

**Pull request merged**
