### PR TITLE
Improve documentation a bit

### PR DESCRIPTION
**Pull request by njvack**
Change references to original github URL to the one in the redcap-tools
organization.

Also tighten up the Installation section of index.rst -- we don't need
to care about the requests dependency, really. Mention the pandas
installation option.

Still TODO: Change the maintainer entry in setup.py.

### CODE REVIEW

**Comment by njvack** [comment]
The other thing that might be worth mentioning in the docs (or just in the README) is that this project is not affiliated with the official Project REDCap.

**Comment by pwildenhain** [comment]
Ah Darn, I also added a small contributing section to the README in #132 -- should that actually live in `contributing.rst`?

👍 For adding the maintainers list
👍 For mentioning this project is not _offficial_ :neckbeard:

**Comment by njvack** [comment]
I'd say that a small contributing section in readme is good (probably link to the one on readthedocs) -- I don't know that I'd think to check the docs for it otherwise.

**Comment by pwildenhain** [comment]
That makes sense, would you also be able to add that in this PR? Link out the the `contributing.rst` from the `README`? And then we'll likely need to update `contributing.rst` at some point haha

**Comment by njvack** [comment]
Yeah, that should be fine, it'll be a day or two, though; I'm on a lil vacation here.

**Comment by pwildenhain** [comment]
@njvack You've done good work here already, I'm just going to merge what you have. Feel free to submit another PR though if there is more you'd like to add.

**Comment by njvack** [comment]
Aww snap, thank you! I 100% forgot I had this outstanding :/

**Pull request merged**
